# https://docs.github.com/en/actions

name: "CI"

on:
    pull_request: ~
    push:
        branches:
            - "main"

jobs:
    coding-standards:
        name: "Coding Standards"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2.3.4"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@2.9.0"
                with:
                    coverage: "none"
                    extensions: "mbstring"
                    php-version: "${{ matrix.php-version }}"

            -   name: "Validate composer.json and composer.lock"
                run: "composer validate --strict"

            -   name: "Install ${{ matrix.dependencies }} dependencies with composer"
                run: "composer update --no-interaction --no-progress"

            -   name: "Check code standard"
                run: "vendor/bin/phpcs"

    static-code-analysis:
        name: "Static Code Analysis"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2.3.4"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@2.9.0"
                with:
                    coverage: "none"
                    extensions: "mbstring"
                    php-version: "${{ matrix.php-version }}"

            -   name: "Install ${{ matrix.dependencies }} dependencies with composer"
                run: "composer update --no-interaction --no-progress && composer i --working-dir=ci"

            -   name: "Run vimeo/psalm"
                run: "ci/vendor/bin/psalm --threads=4"

            -   name: "Run phpstan/phpstan"
                run: "vendor/bin/phpstan a"

    tests:
        name: "Tests"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"
                    - "8.0"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2.3.4"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@2.9.0"
                with:
                    coverage: "none"
                    extensions: "mbstring"
                    php-version: "${{ matrix.php-version }}"

            -   name: "Install ${{ matrix.dependencies }} dependencies with composer"
                run: "composer update --no-interaction --no-progress"

            -   name: "Run unit tests"
                run: "vendor/bin/phpunit"

    infection:
        name: "Infection"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"
                    - "8.0"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2.3.4"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@2.9.0"
                with:
                    coverage: "pcov"
                    extensions: "mbstring"
                    php-version: "${{ matrix.php-version }}"

            -   name: "Install ${{ matrix.dependencies }} dependencies with composer"
                run: "composer update --no-interaction --no-progress"

            -   name: "Run unit tests"
                run: "vendor/bin/infection --threads=4"
